/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ApiAccountRouteImport } from './routes/api/account'
import { Route as ApiChaptersRouteImport } from './routes/api/chapters'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters/$chapterId'
import { Route as ApiAiChapterRouteImport } from './routes/api/ai/chapter'
import { Route as ApiAuthCsrfRouteImport } from './routes/api/auth/csrf'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthUsernameRouteImport } from './routes/api/auth/username'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingStatusRouteImport } from './routes/api/billing/status'
import { Route as ApiChaptersChapterIdRouteImport } from './routes/api/chapters/$chapterId'
import { Route as ApiMediaMediaIdRouteImport } from './routes/api/media/$mediaId'
import { Route as ApiSecurityPasswordRouteImport } from './routes/api/security/password'
import { Route as ApiSecurityQuestionsRouteImport } from './routes/api/security/questions'
import { Route as ApiSecurityStatusRouteImport } from './routes/api/security/status'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAuthRecoveryResetRouteImport } from './routes/api/auth/recovery/reset'
import { Route as ApiAuthRecoveryStartRouteImport } from './routes/api/auth/recovery/start'
import { Route as ApiAuthRecoveryVerifyRouteImport } from './routes/api/auth/recovery/verify'
import { Route as ApiAuthRegisterTotpSetupRouteImport } from './routes/api/auth/register/totp-setup'
import { Route as ApiChaptersChapterIdBackgroundRouteImport } from './routes/api/chapters/$chapterId/background'
import { Route as ApiSecurityTotpDisableRouteImport } from './routes/api/security/totp/disable'
import { Route as ApiSecurityTotpEnableRouteImport } from './routes/api/security/totp/enable'
import { Route as ApiSecurityTotpSetupRouteImport } from './routes/api/security/totp/setup'
import { Route as ApiChaptersChapterIdMediaOrderRouteImport } from './routes/api/chapters/$chapterId/media/order'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChaptersRoute = ApiChaptersRouteImport.update({
  id: '/api/chapters',
  path: '/api/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChapterRoute = ApiAiChapterRouteImport.update({
  id: '/api/ai/chapter',
  path: '/api/ai/chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCsrfRoute = ApiAuthCsrfRouteImport.update({
  id: '/api/auth/csrf',
  path: '/api/auth/csrf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUsernameRoute = ApiAuthUsernameRouteImport.update({
  id: '/api/auth/username',
  path: '/api/auth/username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingStatusRoute = ApiBillingStatusRouteImport.update({
  id: '/api/billing/status',
  path: '/api/billing/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChaptersChapterIdRoute = ApiChaptersChapterIdRouteImport.update({
  id: '/$chapterId',
  path: '/$chapterId',
  getParentRoute: () => ApiChaptersRoute,
} as any)
const ApiMediaMediaIdRoute = ApiMediaMediaIdRouteImport.update({
  id: '/$mediaId',
  path: '/$mediaId',
  getParentRoute: () => ApiMediaRoute,
} as any)
const ApiSecurityPasswordRoute = ApiSecurityPasswordRouteImport.update({
  id: '/api/security/password',
  path: '/api/security/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityQuestionsRoute = ApiSecurityQuestionsRouteImport.update({
  id: '/api/security/questions',
  path: '/api/security/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityStatusRoute = ApiSecurityStatusRouteImport.update({
  id: '/api/security/status',
  path: '/api/security/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRecoveryResetRoute = ApiAuthRecoveryResetRouteImport.update({
  id: '/api/auth/recovery/reset',
  path: '/api/auth/recovery/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRecoveryStartRoute = ApiAuthRecoveryStartRouteImport.update({
  id: '/api/auth/recovery/start',
  path: '/api/auth/recovery/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRecoveryVerifyRoute = ApiAuthRecoveryVerifyRouteImport.update({
  id: '/api/auth/recovery/verify',
  path: '/api/auth/recovery/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterTotpSetupRoute =
  ApiAuthRegisterTotpSetupRouteImport.update({
    id: '/totp-setup',
    path: '/totp-setup',
    getParentRoute: () => ApiAuthRegisterRoute,
  } as any)
const ApiChaptersChapterIdBackgroundRoute =
  ApiChaptersChapterIdBackgroundRouteImport.update({
    id: '/background',
    path: '/background',
    getParentRoute: () => ApiChaptersChapterIdRoute,
  } as any)
const ApiSecurityTotpDisableRoute = ApiSecurityTotpDisableRouteImport.update({
  id: '/api/security/totp/disable',
  path: '/api/security/totp/disable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityTotpEnableRoute = ApiSecurityTotpEnableRouteImport.update({
  id: '/api/security/totp/enable',
  path: '/api/security/totp/enable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityTotpSetupRoute = ApiSecurityTotpSetupRouteImport.update({
  id: '/api/security/totp/setup',
  path: '/api/security/totp/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChaptersChapterIdMediaOrderRoute =
  ApiChaptersChapterIdMediaOrderRouteImport.update({
    id: '/media/order',
    path: '/media/order',
    getParentRoute: () => ApiChaptersChapterIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/security': typeof SecurityRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chapters': typeof ApiChaptersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/billing/success': typeof BillingSuccessRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/api/ai/chapter': typeof ApiAiChapterRoute
  '/api/auth/csrf': typeof ApiAuthCsrfRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRouteWithChildren
  '/api/auth/username': typeof ApiAuthUsernameRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/chapters/$chapterId': typeof ApiChaptersChapterIdRouteWithChildren
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/api/security/password': typeof ApiSecurityPasswordRoute
  '/api/security/questions': typeof ApiSecurityQuestionsRoute
  '/api/security/status': typeof ApiSecurityStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/auth/recovery/reset': typeof ApiAuthRecoveryResetRoute
  '/api/auth/recovery/start': typeof ApiAuthRecoveryStartRoute
  '/api/auth/recovery/verify': typeof ApiAuthRecoveryVerifyRoute
  '/api/auth/register/totp-setup': typeof ApiAuthRegisterTotpSetupRoute
  '/api/chapters/$chapterId/background': typeof ApiChaptersChapterIdBackgroundRoute
  '/api/security/totp/disable': typeof ApiSecurityTotpDisableRoute
  '/api/security/totp/enable': typeof ApiSecurityTotpEnableRoute
  '/api/security/totp/setup': typeof ApiSecurityTotpSetupRoute
  '/api/chapters/$chapterId/media/order': typeof ApiChaptersChapterIdMediaOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/security': typeof SecurityRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chapters': typeof ApiChaptersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/billing/success': typeof BillingSuccessRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/api/ai/chapter': typeof ApiAiChapterRoute
  '/api/auth/csrf': typeof ApiAuthCsrfRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRouteWithChildren
  '/api/auth/username': typeof ApiAuthUsernameRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/chapters/$chapterId': typeof ApiChaptersChapterIdRouteWithChildren
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/api/security/password': typeof ApiSecurityPasswordRoute
  '/api/security/questions': typeof ApiSecurityQuestionsRoute
  '/api/security/status': typeof ApiSecurityStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/auth/recovery/reset': typeof ApiAuthRecoveryResetRoute
  '/api/auth/recovery/start': typeof ApiAuthRecoveryStartRoute
  '/api/auth/recovery/verify': typeof ApiAuthRecoveryVerifyRoute
  '/api/auth/register/totp-setup': typeof ApiAuthRegisterTotpSetupRoute
  '/api/chapters/$chapterId/background': typeof ApiChaptersChapterIdBackgroundRoute
  '/api/security/totp/disable': typeof ApiSecurityTotpDisableRoute
  '/api/security/totp/enable': typeof ApiSecurityTotpEnableRoute
  '/api/security/totp/setup': typeof ApiSecurityTotpSetupRoute
  '/api/chapters/$chapterId/media/order': typeof ApiChaptersChapterIdMediaOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/security': typeof SecurityRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chapters': typeof ApiChaptersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/billing/success': typeof BillingSuccessRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/api/ai/chapter': typeof ApiAiChapterRoute
  '/api/auth/csrf': typeof ApiAuthCsrfRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRouteWithChildren
  '/api/auth/username': typeof ApiAuthUsernameRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/chapters/$chapterId': typeof ApiChaptersChapterIdRouteWithChildren
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/api/security/password': typeof ApiSecurityPasswordRoute
  '/api/security/questions': typeof ApiSecurityQuestionsRoute
  '/api/security/status': typeof ApiSecurityStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/auth/recovery/reset': typeof ApiAuthRecoveryResetRoute
  '/api/auth/recovery/start': typeof ApiAuthRecoveryStartRoute
  '/api/auth/recovery/verify': typeof ApiAuthRecoveryVerifyRoute
  '/api/auth/register/totp-setup': typeof ApiAuthRegisterTotpSetupRoute
  '/api/chapters/$chapterId/background': typeof ApiChaptersChapterIdBackgroundRoute
  '/api/security/totp/disable': typeof ApiSecurityTotpDisableRoute
  '/api/security/totp/enable': typeof ApiSecurityTotpEnableRoute
  '/api/security/totp/setup': typeof ApiSecurityTotpSetupRoute
  '/api/chapters/$chapterId/media/order': typeof ApiChaptersChapterIdMediaOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/faq'
    | '/pricing'
    | '/profile'
    | '/recovery'
    | '/security'
    | '/api/account'
    | '/api/chapters'
    | '/api/health'
    | '/api/media'
    | '/billing/success'
    | '/chapters/$chapterId'
    | '/api/ai/chapter'
    | '/api/auth/csrf'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/username'
    | '/api/billing/checkout'
    | '/api/billing/status'
    | '/api/chapters/$chapterId'
    | '/api/media/$mediaId'
    | '/api/security/password'
    | '/api/security/questions'
    | '/api/security/status'
    | '/api/stripe/webhook'
    | '/api/auth/recovery/reset'
    | '/api/auth/recovery/start'
    | '/api/auth/recovery/verify'
    | '/api/auth/register/totp-setup'
    | '/api/chapters/$chapterId/background'
    | '/api/security/totp/disable'
    | '/api/security/totp/enable'
    | '/api/security/totp/setup'
    | '/api/chapters/$chapterId/media/order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/faq'
    | '/pricing'
    | '/profile'
    | '/recovery'
    | '/security'
    | '/api/account'
    | '/api/chapters'
    | '/api/health'
    | '/api/media'
    | '/billing/success'
    | '/chapters/$chapterId'
    | '/api/ai/chapter'
    | '/api/auth/csrf'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/username'
    | '/api/billing/checkout'
    | '/api/billing/status'
    | '/api/chapters/$chapterId'
    | '/api/media/$mediaId'
    | '/api/security/password'
    | '/api/security/questions'
    | '/api/security/status'
    | '/api/stripe/webhook'
    | '/api/auth/recovery/reset'
    | '/api/auth/recovery/start'
    | '/api/auth/recovery/verify'
    | '/api/auth/register/totp-setup'
    | '/api/chapters/$chapterId/background'
    | '/api/security/totp/disable'
    | '/api/security/totp/enable'
    | '/api/security/totp/setup'
    | '/api/chapters/$chapterId/media/order'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/faq'
    | '/pricing'
    | '/profile'
    | '/recovery'
    | '/security'
    | '/api/account'
    | '/api/chapters'
    | '/api/health'
    | '/api/media'
    | '/billing/success'
    | '/chapters/$chapterId'
    | '/api/ai/chapter'
    | '/api/auth/csrf'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/username'
    | '/api/billing/checkout'
    | '/api/billing/status'
    | '/api/chapters/$chapterId'
    | '/api/media/$mediaId'
    | '/api/security/password'
    | '/api/security/questions'
    | '/api/security/status'
    | '/api/stripe/webhook'
    | '/api/auth/recovery/reset'
    | '/api/auth/recovery/start'
    | '/api/auth/recovery/verify'
    | '/api/auth/register/totp-setup'
    | '/api/chapters/$chapterId/background'
    | '/api/security/totp/disable'
    | '/api/security/totp/enable'
    | '/api/security/totp/setup'
    | '/api/chapters/$chapterId/media/order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RecoveryRoute: typeof RecoveryRoute
  SecurityRoute: typeof SecurityRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiChaptersRoute: typeof ApiChaptersRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMediaRoute: typeof ApiMediaRouteWithChildren
  BillingSuccessRoute: typeof BillingSuccessRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRoute
  ApiAiChapterRoute: typeof ApiAiChapterRoute
  ApiAuthCsrfRoute: typeof ApiAuthCsrfRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRouteWithChildren
  ApiAuthUsernameRoute: typeof ApiAuthUsernameRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingStatusRoute: typeof ApiBillingStatusRoute
  ApiSecurityPasswordRoute: typeof ApiSecurityPasswordRoute
  ApiSecurityQuestionsRoute: typeof ApiSecurityQuestionsRoute
  ApiSecurityStatusRoute: typeof ApiSecurityStatusRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiAuthRecoveryResetRoute: typeof ApiAuthRecoveryResetRoute
  ApiAuthRecoveryStartRoute: typeof ApiAuthRecoveryStartRoute
  ApiAuthRecoveryVerifyRoute: typeof ApiAuthRecoveryVerifyRoute
  ApiSecurityTotpDisableRoute: typeof ApiSecurityTotpDisableRoute
  ApiSecurityTotpEnableRoute: typeof ApiSecurityTotpEnableRoute
  ApiSecurityTotpSetupRoute: typeof ApiSecurityTotpSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chapters': {
      id: '/api/chapters'
      path: '/api/chapters'
      fullPath: '/api/chapters'
      preLoaderRoute: typeof ApiChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chapter': {
      id: '/api/ai/chapter'
      path: '/api/ai/chapter'
      fullPath: '/api/ai/chapter'
      preLoaderRoute: typeof ApiAiChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/csrf': {
      id: '/api/auth/csrf'
      path: '/api/auth/csrf'
      fullPath: '/api/auth/csrf'
      preLoaderRoute: typeof ApiAuthCsrfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/username': {
      id: '/api/auth/username'
      path: '/api/auth/username'
      fullPath: '/api/auth/username'
      preLoaderRoute: typeof ApiAuthUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/status': {
      id: '/api/billing/status'
      path: '/api/billing/status'
      fullPath: '/api/billing/status'
      preLoaderRoute: typeof ApiBillingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chapters/$chapterId': {
      id: '/api/chapters/$chapterId'
      path: '/$chapterId'
      fullPath: '/api/chapters/$chapterId'
      preLoaderRoute: typeof ApiChaptersChapterIdRouteImport
      parentRoute: typeof ApiChaptersRoute
    }
    '/api/media/$mediaId': {
      id: '/api/media/$mediaId'
      path: '/$mediaId'
      fullPath: '/api/media/$mediaId'
      preLoaderRoute: typeof ApiMediaMediaIdRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/api/security/password': {
      id: '/api/security/password'
      path: '/api/security/password'
      fullPath: '/api/security/password'
      preLoaderRoute: typeof ApiSecurityPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/questions': {
      id: '/api/security/questions'
      path: '/api/security/questions'
      fullPath: '/api/security/questions'
      preLoaderRoute: typeof ApiSecurityQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/status': {
      id: '/api/security/status'
      path: '/api/security/status'
      fullPath: '/api/security/status'
      preLoaderRoute: typeof ApiSecurityStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/recovery/reset': {
      id: '/api/auth/recovery/reset'
      path: '/api/auth/recovery/reset'
      fullPath: '/api/auth/recovery/reset'
      preLoaderRoute: typeof ApiAuthRecoveryResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/recovery/start': {
      id: '/api/auth/recovery/start'
      path: '/api/auth/recovery/start'
      fullPath: '/api/auth/recovery/start'
      preLoaderRoute: typeof ApiAuthRecoveryStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/recovery/verify': {
      id: '/api/auth/recovery/verify'
      path: '/api/auth/recovery/verify'
      fullPath: '/api/auth/recovery/verify'
      preLoaderRoute: typeof ApiAuthRecoveryVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register/totp-setup': {
      id: '/api/auth/register/totp-setup'
      path: '/totp-setup'
      fullPath: '/api/auth/register/totp-setup'
      preLoaderRoute: typeof ApiAuthRegisterTotpSetupRouteImport
      parentRoute: typeof ApiAuthRegisterRoute
    }
    '/api/chapters/$chapterId/background': {
      id: '/api/chapters/$chapterId/background'
      path: '/background'
      fullPath: '/api/chapters/$chapterId/background'
      preLoaderRoute: typeof ApiChaptersChapterIdBackgroundRouteImport
      parentRoute: typeof ApiChaptersChapterIdRoute
    }
    '/api/security/totp/disable': {
      id: '/api/security/totp/disable'
      path: '/api/security/totp/disable'
      fullPath: '/api/security/totp/disable'
      preLoaderRoute: typeof ApiSecurityTotpDisableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/totp/enable': {
      id: '/api/security/totp/enable'
      path: '/api/security/totp/enable'
      fullPath: '/api/security/totp/enable'
      preLoaderRoute: typeof ApiSecurityTotpEnableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/totp/setup': {
      id: '/api/security/totp/setup'
      path: '/api/security/totp/setup'
      fullPath: '/api/security/totp/setup'
      preLoaderRoute: typeof ApiSecurityTotpSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chapters/$chapterId/media/order': {
      id: '/api/chapters/$chapterId/media/order'
      path: '/media/order'
      fullPath: '/api/chapters/$chapterId/media/order'
      preLoaderRoute: typeof ApiChaptersChapterIdMediaOrderRouteImport
      parentRoute: typeof ApiChaptersChapterIdRoute
    }
  }
}

interface ApiChaptersChapterIdRouteChildren {
  ApiChaptersChapterIdBackgroundRoute: typeof ApiChaptersChapterIdBackgroundRoute
  ApiChaptersChapterIdMediaOrderRoute: typeof ApiChaptersChapterIdMediaOrderRoute
}

const ApiChaptersChapterIdRouteChildren: ApiChaptersChapterIdRouteChildren = {
  ApiChaptersChapterIdBackgroundRoute: ApiChaptersChapterIdBackgroundRoute,
  ApiChaptersChapterIdMediaOrderRoute: ApiChaptersChapterIdMediaOrderRoute,
}

const ApiChaptersChapterIdRouteWithChildren =
  ApiChaptersChapterIdRoute._addFileChildren(ApiChaptersChapterIdRouteChildren)

interface ApiChaptersRouteChildren {
  ApiChaptersChapterIdRoute: typeof ApiChaptersChapterIdRouteWithChildren
}

const ApiChaptersRouteChildren: ApiChaptersRouteChildren = {
  ApiChaptersChapterIdRoute: ApiChaptersChapterIdRouteWithChildren,
}

const ApiChaptersRouteWithChildren = ApiChaptersRoute._addFileChildren(
  ApiChaptersRouteChildren,
)

interface ApiMediaRouteChildren {
  ApiMediaMediaIdRoute: typeof ApiMediaMediaIdRoute
}

const ApiMediaRouteChildren: ApiMediaRouteChildren = {
  ApiMediaMediaIdRoute: ApiMediaMediaIdRoute,
}

const ApiMediaRouteWithChildren = ApiMediaRoute._addFileChildren(
  ApiMediaRouteChildren,
)

interface ApiAuthRegisterRouteChildren {
  ApiAuthRegisterTotpSetupRoute: typeof ApiAuthRegisterTotpSetupRoute
}

const ApiAuthRegisterRouteChildren: ApiAuthRegisterRouteChildren = {
  ApiAuthRegisterTotpSetupRoute: ApiAuthRegisterTotpSetupRoute,
}

const ApiAuthRegisterRouteWithChildren = ApiAuthRegisterRoute._addFileChildren(
  ApiAuthRegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RecoveryRoute: RecoveryRoute,
  SecurityRoute: SecurityRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiChaptersRoute: ApiChaptersRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiMediaRoute: ApiMediaRouteWithChildren,
  BillingSuccessRoute: BillingSuccessRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRoute,
  ApiAiChapterRoute: ApiAiChapterRoute,
  ApiAuthCsrfRoute: ApiAuthCsrfRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRouteWithChildren,
  ApiAuthUsernameRoute: ApiAuthUsernameRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingStatusRoute: ApiBillingStatusRoute,
  ApiSecurityPasswordRoute: ApiSecurityPasswordRoute,
  ApiSecurityQuestionsRoute: ApiSecurityQuestionsRoute,
  ApiSecurityStatusRoute: ApiSecurityStatusRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiAuthRecoveryResetRoute: ApiAuthRecoveryResetRoute,
  ApiAuthRecoveryStartRoute: ApiAuthRecoveryStartRoute,
  ApiAuthRecoveryVerifyRoute: ApiAuthRecoveryVerifyRoute,
  ApiSecurityTotpDisableRoute: ApiSecurityTotpDisableRoute,
  ApiSecurityTotpEnableRoute: ApiSecurityTotpEnableRoute,
  ApiSecurityTotpSetupRoute: ApiSecurityTotpSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
